PACK = {
    "pack_id": "BANKS_AND_FINANCIALS",
    "label": "Банки",
    "feature_role": "sector_timing",
    "features": [
        "bank_sector_return_20d",
        "bank_sector_return_60d",
        "bank_sector_relative_20d",
        "bank_sector_volatility_20d",
        "bank_sector_index_missing",
        "bank_key_rate_level",
        "bank_key_rate_change_60d",
        "bank_rgbi_driver",
        "bank_macro_missing",
    ],
    "sector_index_source": "MOEX_MOEXFN",
    "feature_prefix": "bank",
    "approved_sources": ["MOEX_IMOEX", "MOEX_MOEXFN", "CBR_KEY_RATE", "MOEX_RGBI"],
    "blocked_sources": [],
    "reason": "Официальный индекс MOEX финансов, ключевая ставка и рынок ОФЗ обновляются автоматически.",
}
