PACK = {
    "pack_id": "REAL_ESTATE_DEVELOPERS",
    "label": "Девелоперы",
    "feature_role": "sector_timing",
    "features": [
        "developer_sector_return_20d",
        "developer_sector_return_60d",
        "developer_sector_relative_20d",
        "developer_sector_volatility_20d",
        "developer_sector_index_missing",
        "developer_key_rate_level",
        "developer_key_rate_change_60d",
        "developer_rgbi_driver",
        "developer_macro_missing",
    ],
    "sector_index_source": "MOEX_MOEXRE",
    "feature_prefix": "developer",
    "approved_sources": ["MOEX_IMOEX", "MOEX_MOEXRE", "CBR_KEY_RATE", "MOEX_RGBI"],
    "blocked_sources": ["CBR_MORTGAGE_VINTAGES"],
    "reason": "Официальный индекс MOEX строительства и факторы ставки обновляются автоматически; ипотечные vintages пока не подключены.",
}
